
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: c2403e6
_src_path: 42-c-template/
project_name: 42-ft_printf
project_type: StaticLib
use_clang_format: true
use_clangd: true
use_premake: true
